/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.futaba;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author David
 */
public class InputRekening extends javax.swing.JFrame {

    /**
     * Creates new form InputRekening
     */
//    String nasabahName;
    public InputRekening() {
        //MYSQL Connection check
//        try{
//            Bridge bd = new Bridge();
//            bd.checkConnect();
//            if (bd.rs.next()) {
//                initComponents();
//                System.out.println("( OK ) Tabel ditemukan !");
//            } else{
////                JOptionPane.showMessageDialog(this, "Tabel error","PERIKSA TABEL",JOptionPane.ERROR_MESSAGE);
//                  System.out.println("( ERROR )Tabel error !");
//            }
//        } catch(Exception e){
////            e.printStackTrace();
//        }
    }
    
    void checkRek(){
        if (tfNoRekening.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Masukkan rekening terlebih dahulu !","Rekening kosong",JOptionPane.ERROR_MESSAGE);
        } else {
            Bridge brd = new Bridge();
            brd.getResultOf("select * from nasabah where no_rek="+tfNoRekening.getText());
            try {
                if (brd.rs.next()) {
                    if (brd.rs.getString("banned").equals("1")) {
                        JOptionPane.showMessageDialog(this, "Rekening anda telah diblokir !","Gagal",JOptionPane.ERROR_MESSAGE);
                    } else{
                        InputPin ip = new InputPin();
                        ip.getNas(brd.rs.getString("nama"),Integer.parseInt(brd.rs.getString("no_rek")));
                        ip.setVisible(true);
                        this.dispose();
                    }
                } else{
                    JOptionPane.showMessageDialog(this, "No rekening salah !","Kesalahan !",JOptionPane.ERROR_MESSAGE);
                    tfNoRekening.setText(null);
                }
            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "Hanya bisa input nomor saja ! ","Kesalahan !",JOptionPane.ERROR_MESSAGE);
            }
        }
    }
    
    void debugCheck(){          
            JOptionPane.showMessageDialog(this, "You entered debug mode !!!","Warning",JOptionPane.WARNING_MESSAGE);
            new DebugMode().setVisible(true);
            this.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tfNoRekening = new javax.swing.JTextField();
        btNext = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Masukkan rekening anda");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Masukkan rekening"));

        tfNoRekening.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfNoRekeningKeyPressed(evt);
            }
        });

        btNext.setText("Selanjutnya >>>");
        btNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfNoRekening)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 222, Short.MAX_VALUE)
                        .addComponent(btNext)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(tfNoRekening, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btNext)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNextActionPerformed
        // TODO add your handling code here:
        if (tfNoRekening.getText().trim().equals("//debug")) {
            debugCheck();
            System.out.println("( WARNING ) //debug command executed");
        } else{
            checkRek();
        }
    }//GEN-LAST:event_btNextActionPerformed

    private void tfNoRekeningKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfNoRekeningKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==KeyEvent.VK_ENTER) {
            checkRek();
        } else if (evt.getKeyCode()==KeyEvent.VK_DELETE){
            tfNoRekening.setText(null);
        }
    }//GEN-LAST:event_tfNoRekeningKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InputRekening.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InputRekening.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InputRekening.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InputRekening.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InputRekening().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btNext;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField tfNoRekening;
    // End of variables declaration//GEN-END:variables
}
