package com.futaba;

import com.sun.glass.events.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author David
 */
public class TransferWindow extends javax.swing.JFrame {

    /** Creates new form TransferWindow */
    String noRek;
    public TransferWindow() {
        initComponents();
    }
    
    void getRek(String rekNomor){
        noRek = rekNomor;
    }
    void doTransfer(){
        if (tfJmlTrnsfr.getText().isEmpty() || tfNoRekTujuan.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Masukkan data dengan lengkap !","Error",JOptionPane.ERROR_MESSAGE);
        } else if (tfNoRekTujuan.getText().equals(noRek)){
            JOptionPane.showMessageDialog(this, "Tidak bisa mentransfer ke akun sendiri !!","Transaksi gagal",JOptionPane.ERROR_MESSAGE);
        } 
        else{
            int currSaldo = 0;
            int strangerSaldo = 0;
            String strangerName = null;
            String stangerStats;
            Bridge bbb = new Bridge();
            Bridge checkAvail = new Bridge();
            try {
                checkAvail.getResultOf("select * from nasabah where no_rek="+tfNoRekTujuan.getText());
                if (checkAvail.rs.next()) {
                    strangerSaldo = Integer.parseInt(checkAvail.rs.getString("saldo"));
                    strangerName = checkAvail.rs.getString("nama");
                    stangerStats = checkAvail.rs.getString("banned");
                    if (stangerStats.equals("0")) {
                       try {
                        bbb.getResultOf("select * from nasabah where no_rek="+noRek);
                        if (bbb.rs.next()) {
                            currSaldo = Integer.parseInt(bbb.rs.getString("saldo"));
                        }
                    } catch (Exception e) {
                            e.printStackTrace();
                        }
                        if (Integer.parseInt(tfJmlTrnsfr.getText()) > (currSaldo - 3000)) {
                            JOptionPane.showMessageDialog(this, "Saldo tidak cukup !","Transfer gagal !",JOptionPane.ERROR_MESSAGE);
                        } else if(Integer.parseInt(tfJmlTrnsfr.getText()) < 10000){
                            JOptionPane.showMessageDialog(this, "Jml transfer minimal Rp.10.000,- !!","Kurang",JOptionPane.ERROR_MESSAGE);
                        } else{
                            int opt = JOptionPane.showConfirmDialog(this, "Lakukan transaksi ke "+noRek +" a/n "+strangerName+"\nDengan jumlah Rp."+tfJmlTrnsfr.getText()+",-\nAkan dikenakan biaya transfer sebesar Rp.3000 !","Konfirmasi",JOptionPane.YES_NO_OPTION);
                            if (opt==JOptionPane.YES_OPTION) {
                                final int totalCurr = currSaldo - Integer.parseInt(tfJmlTrnsfr.getText()) - 3000;
                                final int totalStrange = strangerSaldo + Integer.parseInt(tfJmlTrnsfr.getText());
                                bbb.smtUpdate("UPDATE `nasabah` SET `saldo` = '"+totalCurr+"' WHERE `nasabah`.`no_rek` = "+noRek);
                                checkAvail.smtUpdate("UPDATE `nasabah` SET `saldo` = '"+totalStrange+"' WHERE `nasabah`.`no_rek` = "+tfNoRekTujuan.getText());
                                JOptionPane.showMessageDialog(this, "Transfer berhasil !!!");
                            } else{
                        }
                      } 
                    } else{
                        JOptionPane.showMessageDialog(this, "Akun tujuan sedang dalam masa pemblokiran","Transaksi gagal",JOptionPane.ERROR_MESSAGE);
                    }
                } else{
                    JOptionPane.showMessageDialog(this, "Error, No rek tujuan salah ! Mohon periksa kembali","Error",JOptionPane.ERROR_MESSAGE);
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        tfNoRekTujuan = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfJmlTrnsfr = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Transfer Tunai");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/res/money-bag.png"))); // NOI18N
        jLabel1.setText(" TRANSFER TUNAI");

        tfNoRekTujuan.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        tfNoRekTujuan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfNoRekTujuanKeyPressed(evt);
            }
        });

        jLabel2.setText("Rekening tujuan");

        jLabel3.setText("Jumlah Transfer");

        tfJmlTrnsfr.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        tfJmlTrnsfr.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfJmlTrnsfrKeyPressed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/res/cancel--v1.png"))); // NOI18N
        jButton4.setText("Batalkan");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/res/checkmark.png"))); // NOI18N
        jButton3.setText("Konfirmasi");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfNoRekTujuan, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfJmlTrnsfr, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNoRekTujuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfJmlTrnsfr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(74, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        doTransfer();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void tfJmlTrnsfrKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfJmlTrnsfrKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==KeyEvent.VK_ENTER) {
            doTransfer();
        }
    }//GEN-LAST:event_tfJmlTrnsfrKeyPressed

    private void tfNoRekTujuanKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfNoRekTujuanKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==KeyEvent.VK_ENTER) {
            tfJmlTrnsfr.requestFocus();
        }
    }//GEN-LAST:event_tfNoRekTujuanKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TransferWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TransferWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TransferWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TransferWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TransferWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField tfJmlTrnsfr;
    private javax.swing.JTextField tfNoRekTujuan;
    // End of variables declaration//GEN-END:variables

}
